_BASE_: "../Base-RetinaNet.yaml"
INPUT:
  MIN_SIZE_TRAIN: (800,)
MODEL:
 # WEIGHTS: "/home/ps/DiskA/project/GZY1/Distill_GID_detectron2/RetinaNet_Res18/output_res18/model_final.pth"  
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  RETINANET:
    SMOOTH_L1_LOSS_BETA: 0.1
  #  NUM_CLASSES : 7
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
    SCORE_THRESH_TEST : 0.6 
  OUTPUTS: ["images", "p3", "p4", "p5", "p6", "p7", "gt_labels", "losses", "proposal", "cls_logits", "reg_deltas", "anchors"]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT_DIR: "output_res18"