_BASE_: "../Base-RetinaNet.yaml"
INPUT:
  MIN_SIZE_TRAIN: (800,)
MODEL:
 # WEIGHTS: "/home/ps/DiskA/project/GZY1/Distill_GID_detectron2/RetinaNet_Res50/output_2x_smooth_l1/model_final.pth"
  RESNETS:
    DEPTH: 50
 
  RETINANET:
    SMOOTH_L1_LOSS_BETA: 0.1
   # NUM_CLASSES : 7
  # OUTPUTS is used for distillation,
  # should in ["images", "stem", "res2", ..., "res5", "p2", "p3", ..., "p7",
  #            "proposal", "cls_logits", "reg_deltas", "anchors",
  #            "gt_labels", "gt_boxes", "losses", "results"]
  OUTPUTS: ["images", "p3", "p4", "p5", "p6", "p7", "gt_labels", "losses", "proposal", "cls_logits", "reg_deltas", "anchors"]
OUTPUT_DIR: "output_2x_smooth_l1"